-- ============================================================
-- V1 : Create schema  (Dev — H2 compatible)
-- Runs once on first startup. Flyway tracks via flyway_schema_history.
-- ============================================================

CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    role_id    BIGINT       NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT fk_users_role     FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS courses (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description CLOB,
    duration    VARCHAR(100),
    subjects    VARCHAR(500),
    fees        DOUBLE,
    eligibility VARCHAR(255),
    schedule    VARCHAR(255),
    instructor  VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    image_url   VARCHAR(500),
    created_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    phone        VARCHAR(20)  NOT NULL,
    roll_number  VARCHAR(50)  NOT NULL,
    course       VARCHAR(255) NOT NULL,
    batch        VARCHAR(100),
    standard     VARCHAR(100),
    address      VARCHAR(500),
    status       VARCHAR(20)  DEFAULT 'ACTIVE',
    join_date    DATE,
    fees_paid    DOUBLE,
    total_fees   DOUBLE,
    parent_name  VARCHAR(255),
    parent_phone VARCHAR(20),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT uk_students_email UNIQUE (email),
    CONSTRAINT uk_students_roll  UNIQUE (roll_number)
);
